version: "1.0"
services:
  sso-consumer1-fe:
    build:
      context: .
      args:
        VITE_APP_NAME: "consumer1"
        VITE_PORT: 4000
        VITE_URL: 'http://localhost:4000'
        VITE_API: 'http://localhost:4001'
        VITE_SSO_APP: 'http://localhost:3000'
    image: sso_consumer1_fe_img
    container_name: sso_consumer1_fe_ct
    ports:
      - 4000:4000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - my_network

  sso-consumer2-fe:
    build:
      context: .
      args:
        VITE_APP_NAME: "consumer2"
        VITE_PORT: 5000
        VITE_URL: 'http://localhost:5000'
        VITE_API: 'http://localhost:5001'
        VITE_SSO_APP: 'http://localhost:3000'
    image: sso_consumer2_fe_img
    container_name: sso_consumer2_fe_ct
    ports:
      - 5000:5000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - my_network

networks:
  my_network:
    name: my_network
